SELECT HYBRIS.ORDERS.P_CODE, HYBRIS.ENUMERATIONVALUES.CODE, HYBRIS.PAYMENTMODES.P_CODE  FROM (
SELECT HYBRIS.ORDERS.P_CODE FROM HYBRIS.ORDERS

JOIN HYBRIS.ENUMERATIONVALUES ON HYBRIS.ORDERS.P_STATUS = HYBRIS.ENUMERATIONVALUES.PK

WHERE HYBRIS.ENUMERATIONVALUES.CODE = 'DELIVERED' AND HYBRIS.ORDERS.P_TIMESLOTDELIVERYSTARTDATE BETWEEN '01.06.18 00:00:00,000000000' AND '30.06.18 00:00:00,000000000') TEMP

JOIN HYBRIS.ORDERS ON TEMP.P_CODE = HYBRIS.ORDERS.P_CODE

JOIN HYBRIS.ENUMERATIONVALUES ON HYBRIS.ORDERS.P_DEVICE = HYBRIS.ENUMERATIONVALUES.PK
JOIN HYBRIS.PAYMENTMODES ON HYBRIS.ORDERS.P_PAYMENTMODE = HYBRIS.PAYMENTMODES.PK

WHERE HYBRIS.ENUMERATIONVALUES.CODE = 'Desktop' AND HYBRIS.PAYMENTMODES.P_CODE = 'card';
