SELECT TO_DATE(TO_CHAR((SELECT MIN(ORDERS.CREATEDTS) FROM HYBRIS.ORDERS JOIN HYBRIS.USERS o1 ON HYBRIS.ORDERS.P_USER = o1.PK  WHERE o1.P_UID = o.P_UID),'DD.MM.YY')), P_CODE, P_UID, TO_DATE(TO_CHAR(P_TIMESLOTDELIVERYSTARTDATE,'DD.MM.YY')), P_TOTALPRICE, P_TIMESLOTCOSTZONE, P_STREETNAME       
FROM HYBRIS.ORDERS 
JOIN HYBRIS.USERS o ON HYBRIS.ORDERS.P_USER = o.PK
JOIN HYBRIS.ADDRESSES ON HYBRIS.ADDRESSES.PK = HYBRIS.ORDERS.P_DELIVERYADDRESS
WHERE HYBRIS.ORDERS.CREATEDTS BETWEEN '15.08.18 00:00:00,0' AND '26.08.18 23:59:59,0'
ORDER BY P_TIMESLOTDELIVERYSTARTDATE;