SELECT P_CODE, P_UID, TO_DATE(TO_CHAR(P_TIMESLOTDELIVERYSTARTDATE,'DD.MM.YY')), P_TOTALPRICE, P_TIMESLOTCOSTZONE, P_STREETNAME

FROM HYBRIS.ORDERS

JOIN HYBRIS.USERS ON HYBRIS.ORDERS.P_USER = HYBRIS.USERS.PK

JOIN HYBRIS.ADDRESSES ON HYBRIS.ADDRESSES.PK = HYBRIS.ORDERS.P_DELIVERYADDRESS

WHERE HYBRIS.ORDERS.CREATEDTS BETWEEN '01.06.18 00:00:00,0' AND '25.06.18 23:59:59,0'
ORDER BY P_UID;
