SELECT TO_DATE(TO_CHAR(ORDERS.CREATEDTS,'DD.MM.YY')), HYBRIS.ORDERS.P_CODE, REVIEWQUESTION.P_CODE, REVIEWANSWER.P_ANSWER, HYBRIS.ORDERREVIEW.P_REVIEWCOMMENT
FROM HYBRIS.REVIEWANSWER
JOIN HYBRIS.REVIEWQUESTION ON REVIEWQUESTION.PK = REVIEWANSWER.P_QUESTION
JOIN HYBRIS.ORDERREVIEW ON HYBRIS.ORDERREVIEW.P_ANSWERS LIKE '%' || CAST(HYBRIS.REVIEWANSWER.PK AS VARCHAR2(13)) || '%'
JOIN HYBRIS.ORDERS ON HYBRIS.ORDERREVIEW.P_ORDER = HYBRIS.ORDERS.PK
WHERE P_QUESTION = 8796158601117 AND ORDERS.CREATEDTS BETWEEN '01.04.2018 00:00:00,000000000' AND '30.04.2018 23:59:59,000000000' 
ORDER BY ORDERS.CREATEDTS, HYBRIS.ORDERS.P_CODE;